## Import the relevant libraries

In [1]:
import pandas as pd
import numpy as np

## Loading the data

In [2]:
data_preprocessed = pd.read_csv('C:\\Users\\Petar\\Desktop\\df-preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Create the targets

In [4]:
# find the median of 'Absenteeism Time in Hours'
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
# create targets for our logistic regression
# they have to be categories and we must find a way to say if someone is 'being absent too much' or not
# what we've decided to do is to take the median of the dataset as a cut-off line
# in this way the dataset will be balanced (there will be roughly equal number of 0s and 1s for the logistic regression)

targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
# create a Series in the original data frame that will contain the targets for the regression
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [9]:
# check if dataset is balanced (what % of targets are 1s)
# targets.sum() will give us the number of 1s that there are
# the shape[0] will give us the length of the targets array
targets.sum() / targets.shape[0]

0.45571428571428574

In [10]:
# create a checkpoint by dropping the unnecessary variables
# also drop the variables we 'eliminated' after exploring the weights
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)

In [11]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Select the inputs for the regression

In [12]:
data_with_targets.shape

(700, 12)

In [13]:
# Selects all rows and all columns but the last one (basically the same operation)
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [14]:
# Create a variable that will contain the inputs (everything without the targets)
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [15]:
# standardize the inputs
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [16]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]


In [17]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [18]:
columns_to_scale = ['Month Value', 'Transportation Expense',
       'Age', 'Body Mass Index', 'Children',]

In [19]:
absenteeism_scaler = CustomScaler(columns_to_scale)

C:\Users\Petar\anaconda3\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [20]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\Petar\anaconda3\lib\site-packages\sklearn\base.py:209: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  warnings.warn('From version 0.24, get_params will raise an '


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children'],
             copy=None, with_mean=None, with_std=None)

In [21]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [22]:
scaled_inputs.shape

(700, 11)

## Split the data into train & test and shuffle

In [23]:
# import train_test_split so we can split our data into train and test
from sklearn.model_selection import train_test_split

In [24]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 226         0         0         0         1    -0.102784   
 324         0         0         0         1     1.324766   
 553         0         0         0         1     1.324766   
 512         0         0         0         1     1.039256   
 223         0         0         0         1    -0.102784   
 ..        ...       ...       ...       ...          ...   
 371         1         0         0         0    -1.244823   
 116         0         0         1         0    -1.530333   
 55          0         0         0         0     0.753746   
 385         0         0         0         1    -1.244823   
 111         0         0         1         0     1.610276   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 226               -1.016322 -0.379188        -0.408580          0  0.880469   
 324                0.190942  1.032682         2.649049          0 -0.019280   
 553                2.2131

In [25]:
# declare 4 variables for the split
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [26]:
# check the shape of the train inputs and targets
print (x_train.shape, y_train.shape)

(560, 11) (560,)


In [27]:
# check the shape of the test inputs and targets
print (x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic regression with sklearn

In [28]:
# import the LogisticRegression model from sklearn
from sklearn.linear_model import LogisticRegression

# import the 'metrics' module, which includes important metrics we may want to use
from sklearn import metrics

## Training the model

In [29]:
# create a logistic regression object
reg = LogisticRegression()

In [30]:
# fit our train inputs
reg.fit(x_train,y_train)

LogisticRegression()

In [31]:
# assess the train accuracy of the model
reg.score(x_train,y_train)

0.7732142857142857

### Finding the intercept and coefficients

In [32]:
# get the intercept (bias) of our model
reg.intercept_

array([-1.48349783])

In [33]:
# get the coefficients (weights/parameters) of our model
reg.coef_

array([[ 2.80037469,  0.95161448,  3.11617545,  0.83914529,  0.15900423,
         0.60570975, -0.17001526,  0.27981987, -0.21081556,  0.3482399 ,
        -0.238779  ]])

In [34]:
# check what were the names of our columns
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [35]:
# save the names of the columns in an ad-hoc variable
feature_name = unscaled_inputs.columns.values

In [36]:
# use the coefficients from this table (they will be exported later and will be used in Tableau)
# transpose the model coefficients (model.coef_) and throws them into a df (a vertical organization, so that they can be
# multiplied by certain matrices later) 
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

# add the coefficient values to the summary table
summary_table['Coefficient'] = np.transpose(reg.coef_)

# display the summary table
summary_table

Feature name  Coefficient
0                 Reason_1     2.800375
1                 Reason_2     0.951614
2                 Reason_3     3.116175
3                 Reason_4     0.839145
4              Month Value     0.159004
5   Transportation Expense     0.605710
6                      Age    -0.170015
7          Body Mass Index     0.279820
8                Education    -0.210816
9                 Children     0.348240
10                    Pets    -0.238779

In [37]:
# move all indices by 1
summary_table.index = summary_table.index + 1

# add the intercept at index 0
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

# sort the df by index
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.483498
1                 Reason_1     2.800375
2                 Reason_2     0.951614
3                 Reason_3     3.116175
4                 Reason_4     0.839145
5              Month Value     0.159004
6   Transportation Expense     0.605710
7                      Age    -0.170015
8          Body Mass Index     0.279820
9                Education    -0.210816
10                Children     0.348240
11                    Pets    -0.238779

## Interpreting the coefficients

In [38]:
# create a new Series called: 'Odds ratio' which will show the.. odds ratio of each feature
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [39]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.483498    0.226843
1                 Reason_1     2.800375   16.450810
2                 Reason_2     0.951614    2.589888
3                 Reason_3     3.116175   22.559933
4                 Reason_4     0.839145    2.314388
5              Month Value     0.159004    1.172343
6   Transportation Expense     0.605710    1.832552
7                      Age    -0.170015    0.843652
8          Body Mass Index     0.279820    1.322891
9                Education    -0.210816    0.809923
10                Children     0.348240    1.416572
11                    Pets    -0.238779    0.787589

In [40]:
# sort the table according to odds ratio
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.116175   22.559933
1                 Reason_1     2.800375   16.450810
2                 Reason_2     0.951614    2.589888
4                 Reason_4     0.839145    2.314388
6   Transportation Expense     0.605710    1.832552
10                Children     0.348240    1.416572
8          Body Mass Index     0.279820    1.322891
5              Month Value     0.159004    1.172343
7                      Age    -0.170015    0.843652
9                Education    -0.210816    0.809923
11                    Pets    -0.238779    0.787589
0                Intercept    -1.483498    0.226843

In [41]:
#Reason_3 - Poisoning
#Reason_1 - Various diseases
#Reason_2 - Pregnancy and giving birth
#Reason_4 - Light diseases

## Testing the model

In [42]:
# assess the test accuracy of the model
reg.score(x_test,y_test)

0.75

In [43]:
# find the predicted probabilities of each class
# the first column shows the probability of a particular observation to be 0, while the second one - to be 1
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71333408, 0.28666592],
       [0.58718811, 0.41281189],
       [0.44006047, 0.55993953],
       [0.78156514, 0.21843486],
       [0.08405056, 0.91594944],
       [0.33483021, 0.66516979],
       [0.30006603, 0.69993397],
       [0.13101954, 0.86898046],
       [0.78639897, 0.21360103],
       [0.74898787, 0.25101213],
       [0.49429133, 0.50570867],
       [0.22459161, 0.77540839],
       [0.07121647, 0.92878353],
       [0.73187533, 0.26812467],
       [0.30937676, 0.69062324],
       [0.54690352, 0.45309648],
       [0.55086116, 0.44913884],
       [0.53960522, 0.46039478],
       [0.40216814, 0.59783186],
       [0.05357116, 0.94642884],
       [0.70043738, 0.29956262],
       [0.78156514, 0.21843486],
       [0.42037204, 0.57962796],
       [0.42037204, 0.57962796],
       [0.24789556, 0.75210444],
       [0.74580603, 0.25419397],
       [0.50996641, 0.49003359],
       [0.85688376, 0.14311624],
       [0.20336442, 0.79663558],
       [0.78156514, 0.21843486],
       [0.

In [44]:
predicted_proba.shape

(140, 2)

In [45]:
# select ONLY the probabilities referring to 1s
predicted_proba[:,1]

array([0.28666592, 0.41281189, 0.55993953, 0.21843486, 0.91594944,
       0.66516979, 0.69993397, 0.86898046, 0.21360103, 0.25101213,
       0.50570867, 0.77540839, 0.92878353, 0.26812467, 0.69062324,
       0.45309648, 0.44913884, 0.46039478, 0.59783186, 0.94642884,
       0.29956262, 0.21843486, 0.57962796, 0.57962796, 0.75210444,
       0.25419397, 0.49003359, 0.14311624, 0.79663558, 0.21843486,
       0.36959787, 0.67888875, 0.68507921, 0.52837703, 0.21843486,
       0.53511257, 0.22132578, 0.73701393, 0.40490803, 0.60523192,
       0.2107837 , 0.4522475 , 0.23736826, 0.39847292, 0.82747001,
       0.56804244, 0.69114966, 0.28666592, 0.21944305, 0.20333082,
       0.57634236, 0.32970234, 0.66516979, 0.26962397, 0.8332553 ,
       0.4349806 , 0.88365246, 0.23127477, 0.3342504 , 0.34442735,
       0.69918384, 0.65498433, 0.29248486, 0.79197213, 0.20730747,
       0.26846452, 0.08710093, 0.22132578, 0.73265113, 0.30521861,
       0.22132578, 0.29038395, 0.90443842, 0.46056468, 0.60182

## Save the model

In [46]:
# import the relevant module
import pickle

In [47]:
# pickle the model file
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [48]:
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)